apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${APP_NAME}
  namespace: ${OPENSHIFT_NAMESPACE}
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/nginx-logs
